#ifndef SERVER_CONSTANTS
#define SERVER_CONSTANTS

// ========== COMMON TEXT =============================

// Welcome Message
#define INITIAL_PROMPT \
"=====================================================\n" \
"         Welcome to Mumbai Local Bank!               \n" \
"=====================================================\n" \
"Who are you?\n" \
"1. Admin      \n" \
"2. Customer   \n" \
"3. Manager    \n" \
"4. Employee   \n" \
"\n" \
"Press any other number to exit.\n" \
"Enter the number corresponding to your choice: "

// LOGIN
#define LOGIN_ID "Enter your login ID: "
#define PASSWORD "Enter your password: "
#define INVALID_LOGIN "The login ID specified doesn't exist.\n"
#define INVALID_PASSWORD "The password specified doesn't match.\n"
#define SALT_BAE "666"

// GET ACCOUNT DETAILS
#define GET_ACCOUNT_NUMBER "Enter the account number you're searching for: "
#define GET_CUSTOMER_ID "Enter the customer ID you're searching for: "

#define ERRON_INPUT_FOR_NUMBER \
"Invalid input detected!\n" \
"A numeric value was expected.\n" \
"You'll now be redirected to the main menu.\n"

#define INVALID_MENU_CHOICE \
"Invalid menu choice!\n" \
"You'll now be redirected to the main menu.\n"

#define CUSTOMER_ID_DOESNT_EXIT "No customer could be found for the given ID.\n"
#define CUSTOMER_LOGIN_ID_DOESNT_EXIT "No customer could be found for the given login ID.\n"

#define ACCOUNT_ID_DOESNT_EXIT "No account could be found for the given account number.\n"

#define TRANSACTIONS_NOT_FOUND "No transactions were performed on this account.\n"

// ====================================================

// ========== ADMIN SPECIFIC TEXT======================

// LOGIN WELCOME
#define ADMIN_LOGIN_WELCOME \
"Welcome, Admin! With great power comes great responsibility.\n" \
"Enter your credentials to access the admin panel."

#define ADMIN_LOGIN_SUCCESS "Login successful. Welcome, Admin!"

// ADMIN MENU
#define ADMIN_MENU \
"=====================================================\n" \
"                    ADMIN MENU                       \n" \
"=====================================================\n" \
"1. Add New Bank Employee\n" \
"2. Modify Customer Information\n" \
"3. Modify Employee Information\n" \
"4. Manage User Roles\n" \
"5. Change Admin Password\n" \
"6. Logout\n" \
"7. Exit\n" \
"-----------------------------------------------------\n" \
"Please enter your choice: "

// ADD CUSTOMER
#define ADMIN_ADD_CUSTOMER_PRIMARY \
"Enter the details for the primary customer:\n"

#define ADMIN_ADD_CUSTOMER_SECONDARY \
"Enter the details for the secondary customer:\n"

#define ADMIN_ADD_CUSTOMER_NAME "Customer's name: "
#define ADMIN_ADD_CUSTOMER_GENDER \
"Customer's gender:\n" \
"Enter M for Male, F for Female, or O for Other: "
#define ADMIN_ADD_CUSTOMER_AGE "Customer's age: "
#define ADMIN_ADD_CUSTOMER_AUTOGEN_LOGIN "The autogenerated login ID for the customer is: "
#define ADMIN_ADD_CUSTOMER_AUTOGEN_PASSWORD "The autogenerated password for the customer is: "
#define ADMIN_ADD_CUSTOMER_WRONG_GENDER \
"Invalid gender choice.\n" \
"You'll now be redirected to the main menu.\n"

// ADD ACCOUNT
#define ADMIN_ADD_ACCOUNT_NUMBER "The new account number is: "

// DELETE ACCOUNT
#define ADMIN_DEL_ACCOUNT_NO "Enter the account number you want to delete: "
#define ADMIN_DEL_ACCOUNT_SUCCESS \
"Account has been successfully deleted.\n" \
"Redirecting to the main menu...\n"
#define ADMIN_DEL_ACCOUNT_FAILURE \
"Cannot delete the account since it still has a balance.\n" \
"Redirecting to the main menu...\n"

// MODIFY CUSTOMER INFO
#define ADMIN_MOD_CUSTOMER_ID "Enter the ID of the customer to edit: "
#define ADMIN_MOD_CUSTOMER_MENU \
"Which information would you like to modify?\n" \
"1. Name\n" \
"2. Age\n" \
"3. Gender\n" \
"Press any other key to cancel.\n" \
"Enter your choice: "

#define ADMIN_MOD_CUSTOMER_NEW_NAME "Enter the new name: "
#define ADMIN_MOD_CUSTOMER_NEW_GENDER "Enter the new gender (M/F/O): "
#define ADMIN_MOD_CUSTOMER_NEW_AGE "Enter the new age: "

#define ADMIN_MOD_CUSTOMER_SUCCESS \
"Customer information updated successfully.\n" \
"You'll now be redirected to the main menu.\n"

#define ADMIN_LOGOUT "Logging out now, Admin. Goodbye!\n"

// ====================================================

// ========== CUSTOMER SPECIFIC TEXT===================

// LOGIN WELCOME
#define CUSTOMER_LOGIN_WELCOME \
"Welcome, valued customer!\n" \
"Enter your credentials to access your account."

#define CUSTOMER_LOGIN_SUCCESS "Login successful. Welcome!"

#define CUSTOMER_LOGOUT "Logging out now. Thank you for banking with us!\n"

// CUSTOMER MENU
#define CUSTOMER_MENU \
"=====================================================\n" \
"                   CUSTOMER MENU                     \n" \
"=====================================================\n" \
"1. View Account Details\n" \
"2. Deposit Money\n" \
"3. Withdraw Money\n" \
"4. Check Balance\n" \
"5. View Transaction History\n" \
"6. Change Password\n" \
"7. Transfer Funds\n" \
"8. Apply for Loan\n" \
"9. Provide Feedback\n" \
"10. Logout\n" \
"11. Exit\n" \
"-----------------------------------------------------\n" \
"Please enter your choice: "

#define ACCOUNT_DEACTIVATED \
"Your account has been deactivated.\n" \
"You'll now be redirected to the main menu.\n"

#define DEPOSIT_AMOUNT "Enter the amount to deposit: "
#define DEPOSIT_AMOUNT_INVALID \
"Invalid amount entered.\n" \
"Please try again.\n"
#define DEPOSIT_AMOUNT_SUCCESS \
"Amount deposited successfully!\n"

#define WITHDRAW_AMOUNT "Enter the amount to withdraw: "
#define WITHDRAW_AMOUNT_INVALID \
"Invalid amount or insufficient funds.\n" \
"Please try again.\n"
#define WITHDRAW_AMOUNT_SUCCESS \
"Amount withdrawn successfully!\n"

#define PASSWORD_CHANGE_OLD_PASS "Enter your current password: "
#define PASSWORD_CHANGE_OLD_PASS_INVALID "Incorrect password entered.\n"
#define PASSWORD_CHANGE_NEW_PASS "Enter the new password: "
#define PASSWORD_CHANGE_NEW_PASS_RE "Re-enter the new password: "
#define PASSWORD_CHANGE_NEW_PASS_INVALID \
"Passwords do not match.\n" \
"Please try again.\n"
#define PASSWORD_CHANGE_SUCCESS \
"Password changed successfully!\n"

// ====================================================

// ========== MANAGER SPECIFIC TEXT=====================

#define MANAGER_LOGIN_SUCCESS "Login successful. Welcome, Manager!\n"
#define MANAGER_MENU \
"=====================================================\n" \
"                    MANAGER MENU                     \n" \
"=====================================================\n" \
"1. Activate Customer Accounts\n" \
"2. Deactivate Customer Accounts\n" \
"3. Assign Loan Applications to Employees\n" \
"4. Review Customer Feedback\n" \
"5. Change Password\n" \
"6. Logout\n" \
"7. Exit\n" \
"-----------------------------------------------------\n" \
"Please enter your choice: "

// ====================================================

// ========== EMPLOYEE SPECIFIC TEXT====================

#define EMPLOYEE_LOGIN_SUCCESS "Login successful. Welcome, Employee!\n"
#define EMPLOYEE_MENU  \
"=====================================================\n" \
"                   EMPLOYEE MENU                     \n" \
"=====================================================\n" \
"1. Add New Customer\n" \
"2. Modify Customer Details\n" \
"3. Process Assigned Loans\n" \
"4. Approve or Reject Loan Applications\n" \
"5. Check Loan Status\n" \
"6. Change Password\n" \
"7. Logout\n" \
"8. Exit\n" \
"-----------------------------------------------------\n" \
"Please enter your choice: "

// ====================================================

// ========== CUSTOMER FEEDBACK =========================

#define CUSTOMER_FEEDBACK \
"We value your feedback!\n" \
"Please enter your comments below:\n"

// ==================================================
#define ACCOUNT_FILE "./records/account.bank"
#define CUSTOMER_FILE "./records/customer.bank"
#define EMPLOYEE_FILE "./records/employee.bank"
#define TRANSACTION_FILE "./records/transactions.bank"
#define LOAN_RECORD_FILE "./records/loan.bank"
#define CREDENTIALS_FILE "./functions/admin-credentials.h"

#endif
